services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://dev:yRvdbEvoSZSlP1pOFPw9TGKh0Q4KH1Nf@dpg-d9ssg56gekts7399ip40-a/urlshortener_ufmg
      BASE_URL: http://localhost:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: